### ISSUE TITLE
urllist player

### ISSUE THREAD

**Issue by chrisi1994** [samsamsam-iptvplayer/exteplayer3#3]
for a few days the urllist player says if i want to play a streams : no valid links exist
e.g. http://www.ustream.tv/embed/22214186?html5ui 

Greet

**Comment by samsamsam-iptvplayer** [comment]
Hello this is not main repo. 
Main repo is here:
https://gitlab.com/iptvplayer-for-e2/iptvplayer-for-e2/issues

This stream also not play in my browser.
