### ISSUE TITLE
buffering question

### ISSUE THREAD

**Issue by technic** [samsamsam-iptvplayer/exteplayer3#6]
Hi,
thank you very much for this player!

Is there an option to set pre-buffering duration time or buffer size for http live streams?

**Comment by samsamsam-iptvplayer** [comment]
Hello,

There is no such option at current implementation. Generally additional buffers before injection to video/audio decoders buffer it is worth considering.

Regards,
SSS

**Comment by technic** [comment]
Thanks for the answer. Current implementation also works well for me, so you can consider this feature request as very minor one :)

**Comment by samsamsam-iptvplayer** [comment]
Output buffering has been added (at now only for Broadcom).
To set Linux DVB outputs buffer size you need to use option -b X, where X ис max size of buffered queue in MB.

https://github.com/samsamsam-iptvplayer/exteplayer3/commit/86c7be1cdea3a05c9b3edcd845c3d24c9a2d4499

**Comment by samsamsam-iptvplayer** [comment]
https://github.com/samsamsam-iptvplayer/exteplayer3/commit/1127e2997d9616e09539884e8991b6f66170939e
