### ISSUE TITLE
Picture corruption on m3u8 segment changes

### ISSUE THREAD

**Issue by lprot** [samsamsam-iptvplayer/exteplayer3#7]
When you play: http://www.djing.com/tv/live.m3u8 segments can have different framerate/resolution etc and maybe ffmpeg and/or exteplayer is not aware of that. Sometimes it just plays just showing the corrupted picture, sometimes background turns green, sometimes the receiver totally hangs and you need to repower it.

Tested on DM800HD with OpenPLi homebuild. 
exteplayer3_softfpu_ffmpeg3.4
ffmpeg3.4.2_mipsel_fpu_soft_openssl1.0.2_dash_librtmp_native_rtmp

Gstplayer 1.12.4 and 1.13.1 play that stream no problem on the same receiver (just switching players within the serviceapp)

**Comment by samsamsam-iptvplayer** [comment]
IPTVPlayer use this way that play with exteplayer3 only selected variant of m3u8 playlist.
So, for example:
http://www.djing.com/tv/27992-05.m3u8

Did you check that segment in one variant have different frame rate/resolution? This should not be the case in one variant.

**Comment by lprot** [comment]
Segment params change when they switch from clip to clip...

**Comment by samsamsam-iptvplayer** [comment]
Please check this binary:
http://iptvplayer.vline.pl/temp/exteplayer3_ffmpeg3.4.2

Please note that this is only for test and it can break playback of others streams.

**Comment by lprot** [comment]
Thanks. Testing right now...

**Comment by lprot** [comment]
shouldn't be softfpu?

**Comment by lprot** [comment]
I just get `playing 4097:0:0:0:0:0:0:0:0:0:http%3a//www.djing.com/tv/live.m3u8:DJing
eServiceApp::stop
PlayerBackend::gotMessage - tStart
PlayerApp::processStart: exteplayer3 "http://www.djing.com/tv/live.m3u8"
ExtEPlayer3::handleJsonOutput - unhandled key "EPLAYER3_EXTENDED"
PlayerBackend::recvStopped - retval = 0
PlayerBackend::gotMessage - stop
eServiceApp::gotExtPlayerMessage - stop
eServiceApp::isCurrentlySeekable
resolved to PLAY
eServiceApp::unpause
PlayerBackend::thread_finished
`
And no picture at all. ps says no exteplayer3 is running...

**Comment by lprot** [comment]
Looks like this one is ok. Can you add variant selector to exteplayer itself? ServiceApp got a bug :(
https://github.com/mx3L/serviceapp/issues/20

**Comment by samsamsam-iptvplayer** [comment]
To be able to select variant before av probe there will be need to connect to the server to receive main M3U8 playlist.
This will need to add dependency to another lib like libcurl or write other or write simple HTTPS/HTTP client.

Other possibility is to select variant after av probe but this will increase playabck start. Because in av probe at least one packet from each playlist will be downloaded. So, there will be downloaded each playlist and then segments from each playlist.

Another possibility will be to patch libavformat to select variant there. 

But anyway if this will be done inside exteplayer3/ffmpeg then to exteplayer3 must be pass link to the main playlist. 
As I understand this is not case now. Am I right? So, there will be need to patch laso mx3L/serviceapp

**Comment by lprot** [comment]
Sure ServiceApp needs patching right now as currently we have no way to play some of DJing's in exteplayer by main playlist links. I suppose adding simple check for bitrate tags in m3u8 and selecting highest one could improve exteplayer and make it compatible with main playlists.

**Comment by samsamsam-iptvplayer** [comment]
Did you read what I wrote? "adding simple check" there is no simple solution.

**Comment by lprot** [comment]
Take a look at this one: https://github.com/andoma/movian/blob/b6dd45bb67dc7fb64a2849448a5a7395bb49d356/src/backend/hls/hls.c

**Comment by samsamsam-iptvplayer** [comment]
Please prepare and make merge request if you think that this is "easy".
Did you read that to be able to select something you must first receive content of main playlist?
So, you must become HTTP/HTTPS client.

May I ask why you in your use case siple not use link to variant playlist directly?
For example:
http://www.djing.com/tv/27992-05.m3u8

?

**Comment by lprot** [comment]
Connection speed can vary :(

**Comment by lprot** [comment]
I'm not insisting on simplicity though. Have rate selector in exteplayer just could be a great feature. Gstplayer and Movian do that...

**Comment by samsamsam-iptvplayer** [comment]
"Connection speed can vary :("

There is no plan to add dynamic change of  variant depending on connection speed in near future.
Please feel free to implement this functionality if you need it.

At now please focus on reported issue.

**Comment by lprot** [comment]
Sure. Regarding the issue: I can't reproduce the issue on the version you supplied. Thanks!

**Comment by samsamsam-iptvplayer** [comment]
Fixed.
https://github.com/samsamsam-iptvplayer/exteplayer3/commit/da0bece8c2ef4c5b1c8fa28358647c4405f32c47
