### ISSUE TITLE
Playing is stuttering on some streams

### ISSUE THREAD

**Issue by lprot** [samsamsam-iptvplayer/exteplayer3#8]
Thanks for fixing the player for DJing streams. Works like a magic with b37. Just one problem remains - stuttering. Looks like it's the buffering problem or something as on gstplayer with 8192 buffer it's ok.

The link I'm talking about:
```
PlayerApp::processStart: exteplayer3 "http://www.djing.com/tv/27999-05.m3u8" -u "Enigma2 HbbTV/1.1.1 (+PVR+RTSP+DL;OpenPLi;;;)" -h "Cookie:geo=--; expires=Wed, 14-Mar-2018 08:42:33 GMT; Max-Age=86400; path=/; domain=djing.com
```

Sometimes it just stutters from time to time (not constantly). Sometimes on the segment change the sound becomes silent (the same can happen on gstplayer too btw)

**Comment by samsamsam-iptvplayer** [comment]
Most likely, this is related to the discontinuity of PTS. This should be handled by the drivers calling re-sync. 
On my set-top-box I am not able to reproduce your problem. 
When PTS discontinuity happens then video stop for a second to get sync and then continue playing without stuttering.

**Comment by lprot** [comment]
Does gstreamer process the same stream differently?

**Comment by samsamsam-iptvplayer** [comment]
> I wonder why does gstplayer play this with the less stuttering or not at all then.

I do not know why. I am not able reproduce your problem, so hard to say.

No there is not command line because there is no buffer. 
The buffer is on drivers sites.

**Comment by samsamsam-iptvplayer** [comment]
There is already one issue opened related to buffering:
https://github.com/samsamsam-iptvplayer/exteplayer3/issues/6
